- honeybee_radiance/lib/modifiers.py
- honeybee_radiance/lib/modifierset.py
- honeybee_radiance/modifierset.py
- honeybee_radiance/properties.py
- tests/modifier_set_test.py
Updated modifier-set to match the latest changes in `honeybee-core`.
> fix(modifier-set): update modifier-set

- honeybee_radiance/_extend_honeybee.py
- requirements.txt
Update face writer to match the most recent changes in honeybee-core. This should fix the failing test.
> fix(writer): update face writer

- Dockerfile
- honeybee_radiance/cli/grid.py
- honeybee_radiance/sensorgrid.py
Couple of minor fixes. Tested them on workflows by creating my own docker image and running it as a new operator.
> Couple of fixes to get workflows working

- honeybee_radiance/cli/__init__.py
- honeybee_radiance/cli/sunpath.py
- honeybee_radiance/cli/util.py
- tests/cli/sunpath_cli_test.py
> feat(sunpath): add sunpath commands to cli

- honeybee_radiance/config.py
- tests/sunpath_test.py
I also updated some of the tests since it seems some bugs fixed in the ladybug Sunpath made the hard-coded parts of the honeybee_radiance sunpath tests incorrect.
> fix(config): Update config to use new ladybug_tools install folder

- honeybee_radiance/_extend_honeybee.py
- honeybee_radiance/cli/grid.py
- honeybee_radiance/cli/sky.py
- honeybee_radiance/cli/util.py
- honeybee_radiance/config.py
- honeybee_radiance/lightsource/ground.py
- honeybee_radiance/lightsource/sky/certainirradiance.py
- honeybee_radiance/lightsource/sky/hemisphere.py
- honeybee_radiance/lightsource/sunpath.py
- honeybee_radiance/mutil.py
- honeybee_radiance/primitive.py
- honeybee_radiance/properties/_base.py
- honeybee_radiance/properties/aperture.py
- honeybee_radiance/properties/model.py
- honeybee_radiance/properties/room.py
- honeybee_radiance/putil.py
- honeybee_radiance/reader.py
- honeybee_radiance/sensorgrid.py
- honeybee_radiance/view.py
- honeybee_radiance/writer.py
- tests/material_glow_test.py
- tests/material_light_test.py
This PR includes two commits.
The first commit addresses the issue that is raised in #48. We are changing to_dict to a dictionary to make it easier to translate the modifiers to JSON Schema.
The second commit is merely for fixing the styling issues and misspellings in docstrings. For review only focus on the first commit.
resolves #48
resolves #49
cc: @saeranv
> fix(void): Update Void to_dict method

- honeybee_radiance/cli/sky.py
- honeybee_radiance/cli/sunpath.py
- tests/cli/sunpath_cli_test.py
Since one can generate the wea file for part of the year that should be handled before using the honeybee-radiance command.
I realized the we have not really reviewed the CLI PRs. Starting from this one let's do the reviews and slowly develop a standard that we can enforce among all the projects.
> fix(cli-sunpath): remove analysis period options from sunpath wea subcommand

- honeybee_radiance/modifier/material/__init__.py
- honeybee_radiance/modifier/material/glass.py
- honeybee_radiance/modifier/material/mirror.py
- honeybee_radiance/primitive.py
- tests/material_glass_test.py
- tests/material_light_test.py
- tests/material_metal_test.py
- tests/material_mirror_test.py
- tests/material_plastic_test.py
- tests/primitive_test.py
- tests/rad_string_collection.py
- tests/reader_test.py
This commit also add the mirror Material for Mostapha's branch.
> fix(glass): Enforce use of float for refraction_index in dict

- honeybee_radiance/state.py
- tests/aperture_extend_test.py
Small bug fix and a test here.
> fix(state): Ensure vmtx and dmtx geometry is serialized to dict

- honeybee_radiance/properties/_base.py
- honeybee_radiance/properties/aperture.py
- honeybee_radiance/properties/door.py
- honeybee_radiance/properties/shade.py
- honeybee_radiance/sensor.py
- honeybee_radiance/sensorgrid.py
- honeybee_radiance/state.py
- honeybee_radiance/view.py
- tests/sensor_test.py
- tests/sensorgrid_test.py
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/81
> fix(sensor): Tweak sensor schema to align with other objects

- honeybee_radiance/lib/_loadmodifiers.py
- honeybee_radiance/lib/_loadmodifiersets.py
- honeybee_radiance/lightsource/sky/_skybase.py
- honeybee_radiance/lightsource/sky/cie.py
- honeybee_radiance/lightsource/sky/climatebased.py
- honeybee_radiance/lightsource/sky/sunmatrix.py
- honeybee_radiance/modifierset.py
- requirements.txt
- tests/model_extend_test.py
I am also adding a method to the sky + sun matrix classes to set the north with a vector if the user desires.
> fix(north): Fix north input on sky classmethods

- honeybee_radiance/lightpath.py
- honeybee_radiance/modifier/material/glass.py
- honeybee_radiance/modifier/material/metal.py
- honeybee_radiance/modifier/material/plastic.py
- honeybee_radiance/mutil.py
- honeybee_radiance/properties/model.py
- honeybee_radiance/properties/room.py
- honeybee_radiance/sensorgrid.py
- honeybee_radiance/view.py
- requirements.txt
- tests/lightpath_test.py
This will help with minimizing simulation time by allowing us to export a JSON noting the aperture groups to be run with the grid.
I also added a method to the Room.radiance.properterites to generate a SensorGrid from the Room floors
Lastly, I deleted duplicate ToString methods that were on the SensorGrid and View classes.
> feat(sensorgrid): Add SensorGrid and View room_idnetifier

- honeybee_radiance/cli/translate.py
- tests/cli/translate_cli_test.py
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/121
I just wanted you to be aware of the change @mostaphaRoudsari  and I don't think this requires review since we already discussed it.
> fix(cli): Change --log-file to --output-file in CLI commands

- honeybee_radiance/cli/grid.py
- honeybee_radiance/cli/lib.py
- honeybee_radiance/cli/sky.py
- honeybee_radiance/cli/sunpath.py
- honeybee_radiance/cli/translate.py
- honeybee_radiance/lib/_loadmodifiersets.py
- tests/cli/lib_cli_test.py
This should give @mingbopeng and Konrad what they need to assign default modifiers to the model.
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/89
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/118
> feat(cli): Add commands to retrieve modifiers from the lib

- .gitignore
- Dockerfile
- cli-requirements.txt
- honeybee_radiance/cli/__init__.py
- honeybee_radiance/writer.py
- requirements.txt
- setup.py
The conversation about the best approach for versioning Radiance builds is still on-going. Meanwhile I'm updating the Dockerfile to use the latest build on Mingbo's fork so we can move forward with the process.
> update docker image

- Dockerfile
These changes to the Dockerfile result in the following outcomes:
* The default user on the container is not a root user
* Use `ubuntu:eon` (~79MB) as a base instead of `python:3.7` (~920MB) to drastically reduce image size (resulting image is ~280MB)
* Change final `WORKDIR` from `/opt/run-folder/` to `/home/ladybugbot/run` to match `honeybee-energy` image. This means we will have to also change the workdir on the operator once we change the docker image
> build(docker): set non-root user and reduce image size

- honeybee_radiance/cli/__init__.py
- honeybee_radiance/config.py
- tests/cli/main_cli_test.py
This commit adds a honeybee-radiance config command that returns a full JSON of configuration variables, including the version of Radiance.
> feat(config): Add Radiance version check and add config command

- honeybee_radiance/cli/__init__.py
I can see that this will be useful for debugging down the line.
> style(cli): Add version option

- honeybee_radiance/config.py
It looks like the date will be the most reliable way of evaluating whether a user has a correct version installed given that it's very difficult to evaluate the Radiance version number correctly. It looks like the date might not be present in the same format of older Radiance builds but I catch this case that the date fails to parse and just return None for the date. I assume we'll always be raising exceptions for this case of an unidentified date.
> fix(config): Add property for Radiance version date

- requirements.txt
This is because of the recent change to honeybee-core cli dependencies
> fix(dependencies): add cli to dep

- honeybee_radiance/sensorgrid.py
- honeybee_radiance/writer.py
- tests/sensorgrid_test.py
This commit adds support for grouping sensor groups together.
> add support for sensor grid groups

- honeybee_radiance/cli/translate.py
I realize my mid had gotten twisted about how recipes work. I must remember: everything happens in a different folder than the project folder.
> fix(cli): Remove unnecessary keys from log file

- Dockerfile
Add the ol' binaries to the ol' path.
> fix(docker): add radiance binaries to PATH

- honeybee_radiance/writer.py
> fix(writer): remove typing module

- honeybee_radiance/config.py
This will avoid potential conflicts of people trying to use Accelerad
> fix(config): Grab Radiance version number from mkpmap

- honeybee_radiance/cli/rpict.py
This commit adds rpict to honeybee-radiance. We need [this PR](https://github.com/ladybug-tools/honeybee-radiance-command/pull/143) in honeybee-radiance-command to be merged in first, update the dependencies and then this should work.
cc: @devngc
> feat(cli): add rpict

- .dependabot/config.yml
- dev-requirements.txt
- honeybee_radiance/cli/sky.py
- honeybee_radiance/lightsource/sky/climatebased.py
- tests/sky_climatebased_test.py
I am also fixing a typo in the radiance representation of climate based skies.
> fix(sky): Add a command to adjust skies based on solar vs. visible

- honeybee_radiance/postprocess/annualdaylight.py
This is a pretty big bug that I found in the postprocess module where we were computing the percent of sun-up occupied hours that met the illuminance criteria rather than the percent of all occupied hours that met the criteria. So an occupancy schedule with all night shift hours would have returned a DA of 100% instead of 0%. More info here:
https://discourse.ladybug.tools/t/annual-daylight-issue-with-1-2-2-version/14706
This one looks serious enough that we will have to update the recipe on Pollination.
CC: @mostapharoudsari
> fix(postprocess): Allow occupied hours to be sun-down

- honeybee_radiance/cli/rpict.py
I realize this involves an extra step of copying the view file but it was the easiest way to ensure that the metric appears within the header of the HDR file. I already adjusted the Falsecolor component to search for this metric name and accordingly apply the correct multiplier.
> fix(rpict): Include metric name in resulting HDR header

- honeybee_radiance/cli/postprocess.py
This is what we do for radiation in Ladybug and I think it is closer to what people will expect.
> fix(postprocess): Output radiation values in kWh

- honeybee_radiance/dynamic/group.py
Thanks for finding this bug, Mikkel!
> fix(dynamic): Ensure modifiers appear before geometry in .rad

- honeybee_radiance/cli/raytrace.py
- honeybee_radiance/cli/sky.py
- honeybee_radiance/sensorgrid.py
I am also adding a fix into sensor grid so that things don't fail when a gird has a room identifier for a room that does not exist in the model.
> feat(cli): Add commands for view percent recipe

- honeybee_radiance/cli/raytrace.py
- honeybee_radiance/cli/sky.py
- honeybee_radiance/lightsource/sky/certainirradiance.py
- honeybee_radiance/lightsource/sky/cie.py
- honeybee_radiance/lightsource/sky/climatebased.py
- tests/sky_certain_irradiance_test.py
I am also refactoring a number of things in the last recipe.
> fix(sky): Improve CertainIrradiance sky for Sky View Recipe

- honeybee_radiance/view.py
It seems that the previous implementation had not been done in an air tight manner so we were able to get views with illegal sets of parameters.
> fix(view): Ensure that we cannot get incompatible types and sizes

- .github/workflows/ci.yaml
- honeybee_radiance/cli/dc.py
I'm also fixing/updating some things about the CI.
> fix(scoeff): Implement better solution for white spaces in file paths

- honeybee_radiance/cli/dc.py
More info here:
https://discourse.ladybug.tools/t/solution-exception-invalid-result-folder-on-annualdaylight/13718/51?u=chris
> fix(dc): Ensure that only the octree used triple quotes

- honeybee_radiance/view.py
This commit partly removes the dependency of the view class on honeybee-radiance-command. There's still a dependency on the option classes, which we can probably remove at some point in the future.
For now, I am merging this in order to test the new CI.
> fix(view): Remove dependency of view on honeybee-radiance-command

- honeybee_radiance/cli/grid.py
This change will cause an error until we merge this one:
https://github.com/ladybug-tools/honeybee-radiance-folder/pull/109
> feat(cli grid): add two new commands to split and merge grid folders

- honeybee_radiance/cli/dc.py
- honeybee_radiance/cli/multiphase.py
- honeybee_radiance/reader.py
@chriswmackey and @mostaphaRoudsari, I added a sensor count reader function as mentioned [here](https://github.com/ladybug-tools/honeybee-radiance/pull/663#discussion_r747806002).
> fix(sensor count): Add sensor count helper function

- honeybee_radiance/cli/util.py
This was causing all matrices to be added together.
> fix(cli): Fix major bug in matrix subtraction

- honeybee_radiance/cli/view.py
More information is here:
https://discourse.ladybug.tools/t/multiple-views-for-check-scene/16749/7
> fix(view): Ensure that completely black images don't cause failure

- honeybee_radiance/cli/viewfactor.py
This is needed for the view factor modifiers to align with energy surface temperatures.
> fix(viewfactor): Ensure orphaned objects are grouped with shades

- honeybee_radiance/postprocess/annualdaylight.py
This will make the visualizations in honeybee-vtk a little more helpful by default.
> fix(postprocess): Change the order of metrics for most common cases

- honeybee_radiance/cli/mtx.py
- honeybee_radiance/cli/octree.py
- honeybee_radiance/modifier/material/trans.py
This is what I plan to use in the comfort maps to account for dynamic window constructions.
> fix(octree): Add command to generate octrees from abstracted groups

- honeybee_radiance/properties/model.py
I realized this was creating some bugs in Grasshopper.
> fix(model): Ensure SensorGrids and Views are duplicated with Model

- honeybee_radiance/cli/threephase.py
Should only be merged once https://github.com/ladybug-tools/honeybee-radiance-command/pull/236 has been merged. The requirements should be updated once there is a new release of `honeybee-radiance-command`.
For now the test I added fails because it relies on the above changes to `honeybee-radiance-command`.
> feat(threephase): Allow rgb to illuminance conversion in cli command

- honeybee_radiance/cli/translate.py
- honeybee_radiance/writer.py
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/689
I'm also PEP-8-ifying some of the recent additions to the writer.
> fix(translate): Enable model-to-rad-folder to accept a zipped folder

- honeybee_radiance/cli/grid.py
I would like to use this same command to split CSV files of UTCI air speeds, which are optional and may not include the grid info file. These changes should allow the command to be used for these purposes.
> fix(grid): Enable grid-splitting method to be used for other files

- honeybee_radiance/cli/postprocess.py
- honeybee_radiance/postprocess/annualdaylight.py
- tests/cli/postprocess_cli_test.py
This command is useful for create -viz version of the daylight factor recipe
> fix(cli): add a new command to write daylight factor config file

- honeybee_radiance/cli/multiphase.py
- honeybee_radiance/cli/octree.py
Needs `honeybee-radiance-folder==2.10.4` or whatever version this PR is released under: https://github.com/ladybug-tools/honeybee-radiance-folder/pull/130
> feat(multiphase): Add command for combined octrees and grids

- honeybee_radiance/cli/dc.py
This is needed for imageless glare.
> fix(dc): Add coefficient command without sky mtx

- honeybee_radiance/cli/dc.py
- honeybee_radiance/cli/glare.py
- honeybee_radiance/cli/grid.py
- honeybee_radiance/properties/room.py
- honeybee_radiance/sensorgrid.py
- tests/cli/grid_cli_test.py
- tests/sensorgrid_test.py
This will be needed for imageless glare studies.
> feat(grid): Add methods to generate circular sensor grids

- honeybee_radiance/cli/dc.py
- honeybee_radiance/cli/octree.py
- honeybee_radiance/config.py
- honeybee_radiance/modifier/material/light.py
- honeybee_radiance/writer.py
This should enable the honeybee-radiance docker image to run smoothly.
> fix(config): Add a check for radiance environment variables

- honeybee_radiance/cli/dc.py
- honeybee_radiance/cli/mtx.py
- honeybee_radiance/cli/octree.py
- honeybee_radiance/cli/sky.py
I added a few minor changes to the documentation, which I think will make it easier to understand the documentation.
> Minor changes on the documentation

- honeybee_radiance/cli/multiphase.py
honeybee-radiance was not bumped in other repositories with the latest release.
> fix(multiphase): Trigger new release

- honeybee_radiance/cli/multiphase.py
This is an accidental leftover from debugging!
> fix(multiphase): Remove print function

- honeybee_radiance/properties/_base.py
- honeybee_radiance/properties/room.py
This will enable Radiance properties to show up in the ComparisonReport.
> fix(properties): Add methods to check object equivalency

- .github/workflows/ci.yaml
- honeybee_radiance/cli/sky.py
- honeybee_radiance/cli/view.py
- honeybee_radiance/lightsource/sky/cie.py
- honeybee_radiance/lightsource/sky/climatebased.py
The last release failed because npm was down. I'm also fixing a few typos in docstrings.
> fix(tests): Trigger new release and add tests for Python 10

- honeybee_radiance/lightsource/sky/climatebased.py
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/45
> fix(climatebased): Add an option for a colored climatebased sky

- honeybee_radiance/writer.py
We realized that file size was likely the biggest limiting factor for ShadeMesh workflows. So we no longer triangulate faces by default, allowing some non-planar faces but capitalizing on the fact that quads represent the polygon with fewer vertices. We also round all vertex decimal places to the model tolerance, which should significantly reduce size.
> fix(writer): Optimize ShadeMesh translation for reduced file size

- honeybee_radiance/cli/octree.py
I didn't want to trigger a new release since this functionally is not really supported yet anyway. Using `refactor` instead.
> refactor(octree): Fix adding IES files to scene files

- honeybee_radiance/cli/multiphase.py
- honeybee_radiance/cli/threephase.py
- tests/cli/multiphase_test.py
This also addresses a number of PEP8 styling issues in the module and it fixes a bug that I found in the command.
> fix(multiphase): Refactor aperture-groups command to a function

- honeybee_radiance/dynamic/multiphase.py
Increases the tolerance for normal equivalence checks in the aperture clustering.
> fix(multiphase): Increases normal equivalence tolerance
