ladybug-tools/honeybee-radiance

.releaserc.json, .travis.yml, deploy.sh
I noticed the the online documentation for honeybee-radiance has been overwritten after the last
commit which was a chore(). This change should fix that issue from now on.
=> ci(docs): separate building docs and creating PyPI distribution

honeybee_radiance/cli/grid.py
Add a log-file option to grid split command to have a cleaner way to keep track of the newly generated grids.
=> feat(cli): add log-file for split grid

honeybee_radiance/properties/model.py
This one was pretty deep in there. It seems that I forgot that default input arguments for functions/classes are the same, re-used instance of an object. So this can create big issues when the input is a mutable object type. Now it makes so much sense to my why this is not recommended:
```
def my_function(input=[]):
```
=> fix(model): Fix bug in Model re-serialzation from_dict

MANIFEST.in, honeybee_radiance/config.json, honeybee_radiance/config.py, honeybee_radiance/lib/_loadmodifiers.py, honeybee_radiance/lib/_loadmodifiersets.py, honeybee_radiance/lib/data/__init__.py, honeybee_radiance/lib/data/modifiers/default.mat, honeybee_radiance/lib/data/modifiers/user_library.mat, honeybee_radiance/lib/data/modifiersets/default.json, honeybee_radiance/lib/modifiers.py, honeybee_radiance/lib/modifiersets.py, honeybee_radiance/modifierset.py, honeybee_radiance/mutil.py, honeybee_radiance/primitive.py, honeybee_radiance/properties/_base.py, honeybee_radiance/properties/model.py, honeybee_radiance/putil.py, honeybee_radiance/reader.py, tests/assets/model/test_model.rad, tests/material_glow_test.py, tests/model_extend_test.py, tests/primitive_test.py
This commit changes the libraries to load up from .rad, .mat, or .json files. The data follows a similar structure to honeybee_energy such that we can eventually combine these files with honeybee_energy into a single honeybee_standards repo.
It also adds a config file that allows users to change the folder from which the libraries load up.
=> feat(lib): Load modifiers and modifier sets from files

honeybee_radiance/sensorgrid.py, tests/sensorgrid_test.py
Add count to split grid info. This data is required for several radiance commands.
This change was sitting on my fork for a long time. It's a small change that is useful to set -y in Radiance commands.
=> feat(sensor grid): add count to split info

honeybee_radiance/lib/data/modifiersets/default.json, honeybee_radiance/modifierset.py, tests/modifier_set_test.py
This commit refactors the non-abridged ModifierSet so that it is easier to deconstruct and edit.
It also changes the class names of the subset objects (eg. WallSet) to be specific for radiance (eg. WallModifierSet) so that there is no collision with the schemas of honeybee-energy.
=> fix(modifierset): Refactor non-abridged ModifierSet

honeybee_radiance/modifier/material/mirror.py, honeybee_radiance/mutil.py, tests/material_mirror_test.py
I ran a test and found that the Mirror alaternate_material didn't properly allow Void to be assigned as an input to turn the material invisible. This commit fixes this issue.
=> fix(mirror): Making Void an acceptable alternate material

honeybee_radiance/modifier/material/__init__.py, honeybee_radiance/modifier/material/light.py, honeybee_radiance/modifier/material/mirror.py, honeybee_radiance/modifier/material/plastic.py, honeybee_radiance/mutil.py, honeybee_radiance/primitive.py, tests/material_mirror_test.py
resolves #46
Also addressed all the comments from @chriswmackey in #65 and addressed the limitation that was pointed out in #69 but this iteration differs `void` from `None` for alternate material.
=> feat(material): add mirror material to modifiers

honeybee_radiance/modifier/material/glass.py, honeybee_radiance/modifier/material/mirror.py
Accepting `None` for these cases is a bit implicit and it creates issues when parsing honeybee-schema since `None` indicates to a property that doesn't need to exist at all (rather than a number that needs to be there but just has a default value).
This commit also makes the docstrings of the Mirror alternate_material clearer.
=> docs(glass): Elaborate docstrings to explain implicit code

honeybee_radiance/modifier/material/bsdf.py, tests/material_bsdf_test.py
This commit changes the BSDF dictionary to use a string to store the BSDF data instead of bytes, which are not serialize-able to JSON.
I was not able to compress the string further by removing white spaces since this messed with the re-serialization process (it could not identify the file type as TensorTree or Klems after all white space was removed). Maybe if we recorded the number of white spaces removed in each part so that we could put them back correctly, a strategy like that could work. But, at that point, I question whether we are actually saving much space in the resulting JSON..
=> fix(bsdf): Ensure BSDF is serialize-able to JSON

honeybee_radiance/modifier/material/bsdf.py, honeybee_radiance/modifier/material/metal.py, honeybee_radiance/modifier/material/plastic.py, honeybee_radiance/modifier/material/trans.py, tests/material_metal_test.py
This PR is really only tweaking the docstrings and the default specularity input for the Metal modifier so that we can say Metal is fully supported.
This commit conserves the previous implementation, where everything on the Plastic class is used to describe Metal. It's just that there were still plastic-specific docstrings that have now been tweaked to apply to both Plastic and Metal. Also, the default specularity for metal has been changed to 0.9, since 0.0 (the Plastic default) is not a realistic for metal materials.
=> fix(metal): Use better specularity default for Metal

honeybee_radiance/lightsource/sky/__init__.py, honeybee_radiance/lightsource/sky/_skybase.py, honeybee_radiance/lightsource/sky/certainirradiance.py, honeybee_radiance/lightsource/sky/cie.py, honeybee_radiance/lightsource/sky/climatebased.py, honeybee_radiance/lightsource/sky/hemisphere.py, honeybee_radiance/lightsource/sky/skydome.py, honeybee_radiance/lightsource/sky/skymatrix.py, honeybee_radiance/lightsource/sky/sunmatrix.py, tests/sky_mtx_test.py, tests/sun_mtx_test.py
This PR adds skymtx and sunmtx classes. I decided not to create a daylightmtx class as the separation is actually really helpful to keep the `to_radiance` method clean and clear.
The PR also improves documentation of other sky modules.
=> Add sky and sun matrix

honeybee_radiance/dynamic/__init__.py, honeybee_radiance/dynamic/group.py, honeybee_radiance/dynamic/state.py, honeybee_radiance/dynamic/stategeo.py, honeybee_radiance/properties/_base.py, honeybee_radiance/properties/aperture.py, honeybee_radiance/properties/door.py, honeybee_radiance/properties/model.py, honeybee_radiance/properties/shade.py, honeybee_radiance/sensorgrid.py, honeybee_radiance/view.py, tests/aperture_extend_test.py, tests/door_extend_test.py, tests/model_extend_test.py, tests/sensorgrid_test.py, tests/shade_extend_test.py
This commit creates a separate StateGeometry class for dynamic radiance shades and gets rid of the use of honeybee-core Shades for this purpose.
Resolves https://github.com/ladybug-tools/honeybee-schema/issues/112
Also, now that there are 3 different modules involved with dynamic geometry, I decided to put all of them in the same `dynamic` sub-package.
Lastly, made a small edit to the SensorGrid and View dictionaries: adding the 'type' key into the dictionary in order to keep it in line with all of the other schemas.
=> feat(stategeo): Add StateGeometry class to handle state-assigned shades

honeybee_radiance/properties/model.py, honeybee_radiance/writer.py, requirements.txt, tests/model_extend_test.py
This commit brings honeybee-radiance in line with the recent refactor of honeybee-radiance folder.
I don't expect the edits to result in any significant performance improvements since roughly the same number of checks are still performed (there may be a small improvement form just writing fewer files, albeit with the same overall file contents).
However, the changes greatly simplified the code. Previously, the Model.to.rad_folder method was over 200 lines long, which was realistically as short as it could be given that there were 16 folders that had to be written to.
For the static files (where much of the new simplification occurred), I mostly stuck to writing three files into the folders (.rad, .mat, and .blk). However, I separated the scene in two: 3 envelope files (containing honeybee …
=> fix(model): Update Model.to.rad_folder to work with recent edits

honeybee_radiance/cli/__init__.py, honeybee_radiance/cli/translate.py, honeybee_radiance/lightsource/ground.py, honeybee_radiance/lightsource/sky/_skybase.py, honeybee_radiance/lightsource/sky/certainirradiance.py, honeybee_radiance/lightsource/sky/cie.py, honeybee_radiance/lightsource/sky/climatebased.py, honeybee_radiance/modifier/material/bsdf.py, honeybee_radiance/properties/aperture.py, honeybee_radiance/properties/door.py, honeybee_radiance/properties/shade.py, honeybee_radiance/writer.py, tests/assets/model/model_complete_multiroom_radiance.json, tests/assets/model/model_radiance_dynamic_states.json, tests/assets/modifier/modifier_plastic_generic_wall.json, tests/assets/modifier/modifier_trans_tree_foliage.json, tests/cli/translate_cli_test.py, tests/model_extend_test.py
This commit adds commands to translate Model JSONs to ordinance strings and radiance folders. These will be important for the testing the Rhino radiance plugin that @mingbopeng is working on.
I also fixes a few bugs in model re-serialization as part of this commit.
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/88
=> feat(cli): Add commands to translate model JSON to rad and rad_folder

honeybee_radiance/dynamic/group.py
I forgot that @mostapharoudsari recently made this required and so this commit is adding an identifier key into the states.json.
Nothing to review here @mostaphaRoudsari . I just wanted you to be aware of the fix.
=> fix(group): Ensure identifiers for states go to states.json

honeybee_radiance/__init__.py
I have verified that importing the CLI in `__init__` is unnecessary since there is already [an entry point for the CLI that is specified in setup.py](https://github.com/ladybug-tools/honeybee-radiance/blob/master/setup.py#L26).
You can also see that [the CLI of honeybee-energy runs fine without any of this importing in __init__](https://github.com/ladybug-tools/honeybee-energy/blob/master/honeybee_energy/__init__.py).
Furthermore, this unnecessary importing is causing import errors throughout the Grasshopper plugin since the click dependency cannot be successfully imported in IronPython. So this commit removes it.
=> fix(cli): Remove unnecessary loading of CLI in __init__.py

honeybee_radiance/config.py
I'm fixing part of the config now that I know that the latest Radiance installer on Mac actually installs to usr/local and not the Applications folder, 
I'm also getting rid of the code that automatically finds the version of Radiance that comes with OpenStudio since I realize that the OpenStudio Radiance might never be compatible with the new ladybug tools given that Rob doesn't seem to be maintaining it anymore. But we'll see. Maybe one day we can put it back.
=> fix(config): Improve search for Radiance on Mac

setup.py
I just discovered that the way we exclude tests does not exclude sub-folders of tests with .py files in them.
I will make the change here, in honeybee-radiance-command, in the ladybug-tools-template, and in he other repos that I take care of. But @mostapharoudsari may need to implement this on some of the other repos that he maintains and likely have this issue.
=> fix(pypi): Remove cli tests from the PyPI package

honeybee_radiance/lib/_loadmodifiers.py, honeybee_radiance/lib/_loadmodifiersets.py, honeybee_radiance/lib/modifiers.py, honeybee_radiance/lib/modifiersets.py, honeybee_radiance/properties/model.py, honeybee_radiance/writer.py, requirements.txt, tests/assets/model/model_complete_multiroom_radiance.json, tests/assets/model/model_radiance_dynamic_states.json, tests/model_extend_test.py
This commit removes the global_modifier_set key on the Model object and gets rid of the corresponding bugs it creates.
I also added some extra checks to ensure that users do not overwrite the default modifiers or modifier sets with their own user-added objects. The aim is that these default objects in the library should never be overwritten, ensuring all plugins and ladybug tools libraries are in agreement about these defaults. However, these defaults can always be overridden on any honeybee object, whether it's a Room, or one of the Surface objects.
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/104
=> fix(model): Remove global_modifier_set key from Model schema

honeybee_radiance/cli/grid.py, honeybee_radiance/cli/lib.py, honeybee_radiance/cli/octree.py, honeybee_radiance/cli/sunpath.py, honeybee_radiance/cli/translate.py, honeybee_radiance/dictutil.py, honeybee_radiance/lightsource/dictutil.py, honeybee_radiance/lightsource/sky/_skybase.py, honeybee_radiance/lightsource/sky/cie.py, honeybee_radiance/lightsource/sky/climatebased.py, honeybee_radiance/lightsource/sky/skydome.py, honeybee_radiance/sensorgrid.py, honeybee_radiance/view.py, honeybee_radiance/writer.py, tests/dictutil_test.py, tests/material_glass_test.py, tests/model_extend_test.py, tests/modifier_set_test.py, tests/sensorgrid_test.py
This commit adds a dictutil module to the package, with a dict_to_object method that can re-serialize any dictionary produced from the library back into a honeybee-radiance Python object.  We have implemented similar methods in honeybee-core and honeybee-energy and they have been very useful for keep in the JSON re-serialization code clean on the plugin side of things.
Given that the putil module already handles a lot of these re-serialization issues across honeybee-radiance, I didn't need to add much code in order to enable a package-wide re-serialization function.  I only needed to check the case of a few key top-level assets (ModifierSet, SensorGrid, View) and add a module to re-serialize all of the lightsource objects.
Once we merge this in, I will add the radiance re-serialization …
=> feat(dictutil): Add module to re-serialize any object from dict

honeybee_radiance/dictutil.py
I didn't realize that the putil methods raise a NotImplementedError. It's such a small bug that it's not worth a new release, though.
=> perf(dictutil): Ensure correct exception is caught

.travis.yml, Dockerfile
Similar to honeybee-energy docker we have to explicitly add pydantic and honeybee-schema to pip install.
I also updated Radiance to the latest version which is required for annual studies.
=> fix(docker): add honeybee-schema and update Radiance

honeybee_radiance/properties/_base.py, honeybee_radiance/properties/model.py, honeybee_radiance/properties/room.py, honeybee_radiance/sensor.py, honeybee_radiance/sensorgrid.py, honeybee_radiance/view.py, honeybee_radiance/writer.py, tests/lightpath_test.py, tests/model_extend_test.py, tests/room_extend_test.py, tests/sensor_test.py, tests/sensorgrid_test.py, tests/view_test.py
This commit adds several improvements around the SensorGrid and View classes:
* Include SensorGrids and Views as properties under ModelRadianceProperties
* Write SensorGrid and View files as part of the Model.to.rad_folder method
* Add ability to move, rotate, scale reflect sensor grids + views
* Ensure that the grids + views get moved, rotated, scaled whenever the Model is transformed or the units system is changed
* Added a property to the SensorGrid class to optionally store the mesh information for better visualization
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/230
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/229
Resolves https://github.com/ladybug-tools/honeybee-radiance/issues/100
=> feat(model): Add sensor_grid and views under ModelRadianceProperties

honeybee_radiance/modifier/material/mirror.py
Importing the object from another module fails on WSL. This change should fix it.
=> fix(primitive): minimize import to modules

honeybee_radiance/lightsource/sky/skydome.py, tests/assets/sky/sky.dome
The header for ground and sky was assigned in reverse order. That is now fixed.
=> fix(sky-dome): fix header for ground and sky

honeybee_radiance/modifierset.py, honeybee_radiance/properties/_base.py, honeybee_radiance/properties/aperture.py, honeybee_radiance/properties/door.py, honeybee_radiance/properties/face.py, honeybee_radiance/properties/model.py, honeybee_radiance/properties/room.py, honeybee_radiance/sensorgrid.py, honeybee_radiance/view.py, honeybee_radiance/writer.py
The base_geometry  will be useful for visualization purposes.
I am also putting back the older behavior of the SensorGrid and View identifiers. So identifiers are now used to specify the filenames in the model folder (instead of the display_name).  In accordance with this, I am going to get rid of the addition of UUID text whenever a user specifies a name for a sensor grid, view, or modifier on the Grasshopper interface.  While this will almost certainly result in ID conflicts at some point, there are usually not that many modifiers or grids in a model that the user won't be able to do some conflict resolution.  Geometry, on the other hand, doesn't seem to be worth the risk of un-resolvable ID collisions.  So I'll always give this a unique ID when it's created.
CC: @devngc
=> fix(sensorgrid): Add base_geometry property for SensorGrid

Dockerfile, deploy.sh
- Reduce image size
- To enable faster pulls
@mostaphaRoudsari I see that this is built in `deploy.sh` but I'm not sure where in the CI process this gets called so I'm not positive that `curl` is available. As long as it is, it should be fine.
The changes here reduce uncompressed image size `1.02GB` -> `0.33GB`.
=> fix(docker): reduce image size

Dockerfile, deploy.sh
- Handle different radiance hashes in archive name
- So that the docker build works
There's a slight difference in the hash length that is used in the .zip vs the .tar.gz of radiance that is needed for the image build. `5.3.fc2a261076` vs `5.3.fc2a2610`. So the build arg that was used before would get the .zip but not find the correct folder from the .tar.gz. This normalizes the name by renaming the untarred archive to just be `radiance/`.
I tested this on my fork [here](https://github.com/tymokvo/honeybee-radiance/runs/1982783390?check_suite_focus=true) and it seems to work.
=> fix(deploy): normalize radiance name

honeybee_radiance/cli/postprocess.py, honeybee_radiance/postprocess/annualdaylight.py
With this change every metric will be generated under a separate subfolder.
The change also adds the filtered information for grids_info to each subfolder. This file can be used by handlers to ensure the order of the outputs will match the order of the input grids.
=> Restructure annual daylight metric files

honeybee_radiance/cli/translate.py, requirements.txt
Just enabling the model-to-rad-folder command to accept pkl files instead of JSON means that practically all Radiance recipes can accept much larger models without maxing our memory.
I think we will still use HBJSON for the majority of cases but I can see that this will be handy for the edge cases.
=> fix(translate): Permit the use of a pkl file for Honeybee Model

docs/cli.rst, docs/cli/index.rst, docs/conf.py, docs/index.rst, honeybee_radiance/lightsource/sky/_skybase.py, honeybee_radiance/lightsource/sky/cie.py
Hi @chriswmackey,
Here is my first pass to this library. This one has a a few unique things and thought would be a good one to start with before we move on to the rest of the libraries. 
1.  **CLI group names:**
The main issue here is that there are two CLI groups (mtx and postprocess) where the filenames differ from the group names. To address this I created a hash table where each library can include `rst_filename: group_name` pairs for these special cases. This means that if future CLI groups fall in this special case they will need to be added to the hash table for the group documentation to be generated properly. If we don't want to rely on people adding them to the hash table manually we could possibly automate this by reading the file with the CLI code and extract the name of the …
=> docs(cli): Improve CLI documentation structure

honeybee_radiance/postprocess/annualdaylight.py
It will simplify the handlers a lot if they always follow the same convention of the the files bearing the grid name but the parent folder bears the metric name.
This commit fixes the issue reported here:
https://discourse.ladybug.tools/t/hb-1-2-0-udi-low-and-udi-up-not-outputting-any-results/13740
CC: @mostapharoudsari
=> fix(postprocess): Simplify the naming convention of output files

honeybee_radiance/writer.py, tests/assets/model/two_rooms_no_grids.hbjson, tests/cli/translate_cli_test.py
fix #494
I also reproduced the `write empty folder is model does not contain property` behaviour for BSDF materials and dynamic properties. I am not sure how useful the empty BSDF folder is but having an empty `state.json` for dynamic properties makes sense as I assume the file is used in a similar manner to the `_info.json`
=> Always write grid folder with _info.json

honeybee_radiance/cli/translate.py, honeybee_radiance/writer.py, tests/cli/translate_cli_test.py
This commit adds options to perform checks for the presence of grids or views and so that an explicit exception can be raised for recipes requiring these inputs. This seems better than writing empty folders and failing silently.
It also seems more pythonic and elegant for two reasons:
- Explicit is better than implicit (it's much better to get an error about what's wrong than a silent failure)
- Beautiful is better than ugly (why should I get a bunch of empty folders when they are not needed).
=> fix(writer): Replace writing of empty folders with explicit exception

honeybee_radiance/sensorgrid.py, honeybee_radiance/view.py, honeybee_radiance/writer.py, tests/cli/translate_cli_test.py
Use full identifier instead of identifier to avoid merging sensor grids that are part of different groups.
=> Improve group by identifier

honeybee_radiance/cli/sky.py, honeybee_radiance/lightsource/dictutil.py, honeybee_radiance/lightsource/sky/_skybase.py, honeybee_radiance/lightsource/sky/certainirradiance.py, honeybee_radiance/lightsource/sky/cie.py, honeybee_radiance/lightsource/sky/climatebased.py, honeybee_radiance/lightsource/sky/strutil.py, honeybee_radiance/lightsource/sunpath.py, tests/cli/sky_cli_test.py, tests/sky_certain_irradiance_test.py, tests/sky_cie_test.py, tests/sky_climatebased_test.py
These can be used within all sky-based recipes so that we don't need a different recipe for each sky type. The new `honeybee-radiance sky from-string` command provides a single function to process any sky string into a sky file for recipes.
@mostaphaRoudsari , if you have any comments on the string representations, please let me know and I am happy to adjust them. I might merge this tomorrow so that [I can begin addressing this other schema issue](https://github.com/ladybug-tools/honeybee-schema/issues/204).
CC: @devngc
=> fix(sky): Add methods to serialize skies from strings

.dependabot/config.yml, honeybee_radiance/cli/raytrace.py, tests/cli/raytrace_test.py
I am also taking the opportunity to stop dependabot from updating Sphinx as it keeps breaking things.
I am pretty sure that I did this correctly since the daylight-factor command provided a pretty clear example. And I used honeybee-plus library to figure out what the specific type of rcalc should be for the different metrics (eg. illuminace, vs. irradiance vs. luminance). The output of the test that I added seems to be correct.
I hope that you don't mid that I just merge this, @mostaphaRoudsari , so that I can continue making the recipe.
=> feat(raytrace): Add command for PIT ray-tracing w/ post-processing

honeybee_radiance/modifier/material/bsdf.py, honeybee_radiance/writer.py
We will need this as a workaround for now while optional artifacts are not fully supported in queenbee.
I'm also removing unused dependencies from the bsdf module.
=> fix(bsdf): Always include bsdf in Model-Rad-Folder for now

deploy.sh
Apparently, the new Radiance isn't compatible with the slim image of Linux.
=> fix(docker): Revert version of Radiance in the docker image

deploy.sh, honeybee_radiance/writer.py
This information in this file is not necessary but having it there allows us to get around a bug in Argo related to optional artifacts.
=> fix(writer): Add BSDF info file

honeybee_radiance/dynamic/group.py, honeybee_radiance/dynamic/state.py
A unique modifier is needed for each aperture group when calculating multiple view matrices is one go. This replaces the default "white_glow" with a glow modifier with a unique name for the given aperture group.
=> feat(dynamic): Unique glow modifier per aperture group

honeybee_radiance/cli/lib.py, honeybee_radiance/cli/view.py, honeybee_radiance/lib/_loadmodifiers.py, honeybee_radiance/lib/_loadmodifiersets.py
This should satisfy what @MingboPeng needs in order to load local user-defined standards with the .NET bindings.
=> feat(cli): Add command to get standards folder as ModelEnergyProperties

honeybee_radiance/modifier/material/bsdf.py
This is probably more stylistic than anything but it's probably good practice.
=> fix(bsdf): Ensure / is always used instead of \

honeybee_radiance/cli/dc.py
It seems that there's an issue in Radiance's `rflumtx` command in that it doesn't pass the file paths in quotes to the `rcotrib` command that is running under the hood (resulting in the `rcontrib` command failing in spite of the input for the `rfluxmtx` command input being valid with all file paths in quotes). Changing this command to use relative paths should provide a workaround for the current recipes but we should probably bring this issue up on the Radiance forum.
=> fix(dc): Ensure that scoeff can run using relative paths

honeybee_radiance/view.py
I put this in the `standardize_fisheye` method to avoid editing the HB View component in GH.
=> feat(view): Allow 360 fisheyes for view type -vta

honeybee_radiance/properties/model.py, honeybee_radiance/writer.py
In models with Surface boundary conditions, our previous strategy of only writing one of the two geometries was causing incorrect modifiers to be used in the resulting simulation.
Fore example, only writing the ceiling geometry (and not the ceiling + floor) means the the floor of the room above has the reflectance of a ceiling (at 0.8 instead of 0.2 by default). To address this, I am using the same strategy that has been working well for exterior geometries in the comfort maps, which is to offset one of the geometries by 2*tolerance so that we can assign the different modifiers to floor vs. ceiling. I tested this and it seems to work well.
=> fix(model): Ensure that interior modifiers aren't lost

honeybee_radiance/modifier/material/glass.py, honeybee_radiance/modifier/material/trans.py
It seems that there might have been a bug in the average_transmittance property. I took all of the new properties from page 23 of this Radiance manual:
http://www.jaloxa.eu/resources/radiance/documentation/docs/radiance_cookbook.pdf
=> fix(trans): Fix several of the Trans material properties

honeybee_radiance/modifier/material/trans.py, tests/material_trans_test.py
I've come to realize that I have been using the Trans material wrong for all of these years because the properties in Radiance are not what they initially seem. And they are definitely not what you would get from any product manufacturer. So I am adding this classmethod so that we can actually construct the material from transmittance and reflectance.
=> fix(trans): Add classmethod to create material from average properties

honeybee_radiance/postprocess/annualdaylight.py
After working with config files in Pollination apps I realized that we can remove one extra step in the recipes by writing the config file directly.
=> fix: write config file directly

honeybee_radiance/cli/dc.py, honeybee_radiance/cli/mtx.py, honeybee_radiance/cli/sky.py
Some users had pointed out that they were unable to run thermal comfort maps for run periods of just nighttime hours because all of the shortwave radiance calculations were not set up to run with Weas of nighttime hours. This commit fixes this and will just have the commands output blank files when there are no sun-up hours to simulate.
=> fix(cli): Enable the simulation of night-time Weas

honeybee_radiance/cli/octree.py, honeybee_radiance/postprocess/electriclight.py
I feel like blacked-out apertures is a better default behavior for all of the recipes that aren't capable of modeling dynamic apertures. At least this will make it clear to people when a certain recipe does not support dynamic groups.
It's also the default that I need in the comfort mapping workflows.
=> fix(octree): Add an option to keep aperture groups as black

honeybee_radiance/properties/room.py
Using the display name as a base seems to be much more preferable, even though it carries a higher risk of clashing between grids.
But we've been generating it from the display_name in Grasshopper without issues.
=> fix(room): Generate grid names from display_name instead of ID

honeybee_radiance/cli/octree.py
It seems that somehow using the same name as the dynamic window info causes an error with dynamic shade info.
=> fix(cli): Change name of output file to avoid naming conflict

honeybee_radiance/cli/multiphase.py
If `include_static` is used and no aperture groups are present in the model, the static state will be included in `two_phase.json` as well.
=> fix(multiphase): Allow static to be dynamic without dynamic groups

honeybee_radiance/cli/multiphase.py, honeybee_radiance/lightpath.py, honeybee_radiance/sensorgrid.py, honeybee_radiance/view.py, requirements.txt, tests/assets/sample_office/model/folder.cfg, tests/lightpath_test.py
This will ensure that they are always called the same name in the model, model folder and results folder.
=> fix(static apertures): change the default name to __static_apertures__

honeybee_radiance/lightpath.py
This is a temporary fix. It will not do work with aperture groups.
=> fix(lightpath): Add static apertures if they are the only light path

honeybee_radiance/cli/multiphase.py, honeybee_radiance/cli/threephase.py
Hi, @mikkelkp - I don't dare to merge this in as it might break other functionalities but we should use the `full_id` as the identifier for sensor grids instead of the `identifier`.
Otherwise, we will face issues like this: https://github.com/ladybug-tools/honeybee-radiance-postprocess/pull/67
=> fix(dynamic daylight): use full_id instead of identifier

honeybee_radiance/cli/multiphase.py
This is a more general solution and not exclusively for static apertures.
=> fix(multiphase): Avoid octree creation if light path is filtered out

honeybee_radiance/modifier/material/glass.py, tests/material_glass_test.py
It looks like the transmissivity function creates negative values when given very small transmittances. This fixes the issue.
=> fix(glass): Ensure tiny transmittance values don't create errors

honeybee_radiance/cli/multiphase.py, honeybee_radiance/cli/octree.py
This is used in Grasshopper so we cannot use f-strings.
=> fix(multiphase): Remove f-strings from modules

honeybee_radiance/cli/octree.py
This is the solution used in two-phase-daylight-coefficient.
=> fix(octree): Allow from-folder-static with many aperture groups
